### ISSUE TITLE
Index a Project via HTTP API

### ISSUE THREAD

**Issue by farhoud** [soverant/lattice#11]
**Title:** Implement Endpoint to Index a Project

**Description:**
Create an HTTP API endpoint to index a project by providing the project path and main function.

**Acceptance Criteria:**
- Implement a POST endpoint at `/index`.
- The endpoint should accept a JSON body with `path` and `main` fields.
- Return a success message upon successful indexing.

**Request Example:**
```json
{
  "path": "/path/to/your/project",
  "main": "main.py"
}
```

**Response Example:**
```json
{
  "status": "success",
  "message": "Project indexed successfully."
}
```

**Tasks:**
- [ ] Define the `/index` endpoint.
- [ ] Validate the input fields (`path` and `main`).
- [ ] Implement the indexing functionality.
- [ ] Return a JSON response with the status and message.
