### ISSUE TITLE
Search Code via HTTP API

### ISSUE THREAD

**Issue by farhoud** [soverant/lattice#12]
**Title:** Implement Endpoint to Search for Code

**Description:**
Create an HTTP API endpoint to search for code using human language queries.

**Acceptance Criteria:**
- Implement a GET endpoint at `/search`.
- The endpoint should accept a query parameter `query`.
- Return a list of search results with file names, line numbers, and code snippets.

**Request Example:**
```
GET /search?query=function+that+calculates+factorial
```

**Response Example:**
```json
{
  "status": "success",
  "results": [
    {
      "file": "utils.py",
      "line": 10,
      "code": "def factorial(n):"
    },
    {
      "file": "math_helpers.py",
      "line": 5,
      "code": "def compute_factorial(number):"
    }
  ]
}
```

**Tasks:**
- [ ] Define the `/search` endpoint.
- [ ] Validate the `query` parameter.
- [ ] Implement the search functionality.
- [ ] Return a JSON response with the status and results.
