### ISSUE TITLE
Implement `index` Command for Lattice CLI

### ISSUE THREAD

**Issue by farhoud** [soverant/lattice#14]
**Title:** Implement `index` Command for Lattice CLI

**Description:**
Create a CLI command to index a project by providing the project path and main function.

**Acceptance Criteria:**
- Implement the `index` command.
- The command should accept `--path` and `--main` arguments.
- Call the HTTP API to index the project.
- Display a success message upon successful indexing.

**Usage Example:**
```bash
lattice index --path /path/to/your/project --main main.py
```

**Tasks:**
- [ ] Define the `index` command.
- [ ] Parse the `--path` and `--main` arguments.
- [ ] Call the HTTP API to index the project.
- [ ] Display the response message.
