### ISSUE TITLE
 Implement `search` Command for Lattice CLI

### ISSUE THREAD

**Issue by farhoud** [soverant/lattice#15]
**Title:** Implement `search` Command for Lattice CLI

**Description:**
Create a CLI command to search for code using human language queries.

**Acceptance Criteria:**
- Implement the `search` command.
- The command should accept a `--query` argument.
- Call the HTTP API to search for code.
- Display the search results.

**Usage Example:**
```bash
lattice search --query "function that calculates factorial"
```

**Tasks:**
- [ ] Define the `search` command.
- [ ] Parse the `--query` argument.
- [ ] Call the HTTP API to search for code.
- [ ] Display the search results.
